### ISSUE TITLE
uuidToPhysicalPath should handle the language

### ISSUE THREAD

**Issue by erral** [plone/plone.app.uuid#12]
The same as in https://github.com/plone/plone.outputfilters/issues/51

**Comment by mauritsvanrees** [comment]
I have closed https://github.com/plone/plone.outputfilters/issues/52 in favour of the current issue, as it should be fixed in `plone.app.uuid`. Below follows your original comment.

------------

When using plone.app.multilingual in a site, images and files added to the `assets` folder are shown automatically in all languages thanks to the [LIF](https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/content/lif.py#L7).

But those images share the UID across languages.

So if you add an image to the assets folder in English, you go to the Spanish part of the site, and reference that image from the `media`  folder (spanish counterpart of the `assets` folder), the generated URL is `/en/assets/file` instead of `/es/media/file`. This is because [uuidToObject](https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/browser/resolveuid.py#L25) and [uuidToUrl](https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/browser/resolveuid.py#L16) look for the relevant UID and return the first found object.

I think that language should be taken into account in the catalog search to return the corresponding item.

cc: @libargutxi @ionlizarazu

**Comment by erral** [comment]
Yep, I have opened it here after seeing your issue in plone.restapi 😅

 I will try to add a PR with a test in the coming days

**Comment by erral** [comment]
I can't reproduce the error anymore in classic, either Plone 5 or 6.

**Comment by davisagli** [comment]
plone.app.uuid does not support multiple items with the same UID -- it uses the ZCatalog's UUIDIndex which is optimized by only storing one document id per UUID, rather than a set. So, if this does show up again, it may require changing the indexing strategy when LIFs are in use

**Comment by erral** [comment]
I am closing this since I can't reproduce the error that lead to open the issue.
